### ISSUE TITLE
Cannot inject pheanstalks in my own bundle

### ISSUE THREAD

**Issue by sandermarechal** [armetiz/LeezyPheanstalkBundle#33]
It is not possible to inject pheanstalks in my own bundles. My config:

``` yaml
leezy_pheanstalk:
    pheanstalks:
        default:
            server: localhost
            default: true
```

The service IDs `leezy.pheanstalk` and `leezy.pheanstalk.default` are generated by the ProxyCompilerPass. That means that in MyBundleExtension I cannot create a new Reference to these services because they do not exist yet. Effectively I cannot inject them. Symfony says:

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
The service definition "leezy.pheanstalk" does not exist.
```

Is there a specific reason why you create these services in a CompilerPass and not directly in the LeezyPheanstalkExtension?
