### ISSUE TITLE
Unable to set custom proxy service through config after update to 2.1.4 version

### ISSUE THREAD

**Issue by munkie** [armetiz/LeezyPheanstalkBundle#38]
My config

``` yaml
leezy_pheanstalk:
    enabled: true
    pheanstalks:
        primary:
            server: %beanstalkd_server%
            default: true
            proxy: lighthouse.core.job.pheanstalk
```

Where **lighthouse.core.job.pheanstalk** is service that extends _Pheanstalk_Proxy_ and adds some extra functionality

But cache clear fails with error 

```
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The service definition "lighthouse.core.job.pheanstalk" does not exist.   
```

I've debugged a little and found out that at the moment when _LeezyPheanstalkExtension_ class creates DI Definition of connections there are only few services defined in container and my services is not set in container yet, though i configure it in common way it is done in Symfony.
