### ISSUE TITLE
Prefixing tube names.

### ISSUE THREAD

**Issue by h4cc** [armetiz/LeezyPheanstalkBundle#39]
I am missing the feature, to be abled to prefix tubes per server.

Something like this:

```
leezy_pheanstalk:
    enabled: true
    pheanstalks:
        primary:
            server: 127.0.0.1
            port: 11300
            timeout: 60
            tube_prefix: production_
            default: true
```

What do you think?
